export {default as Home} from './Home'
export {default as Profile} from './Profile'
export {default as Message} from './Message'
export {default as Explore} from './Explore'
export {default as Error} from './Error'
export {default as Dashboard} from './Dashboard'